<?php

namespace solicitudMonitoria\CursosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstudianteCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudianteCursoRepository extends EntityRepository
{
}
