<?php

namespace solicitudMonitoria\JefeSeccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CalificacionEstudianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalificacionEstudianteRepository extends EntityRepository
{
}
