<?php

namespace solicitudMonitoria\JefeSeccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JefesSeccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JefesSeccionesRepository extends EntityRepository
{
}
