<?php

namespace Proxies\__CG__\solicitudMonitoria\EstudianteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Solicitudes extends \solicitudMonitoria\EstudianteBundle\Entity\Solicitudes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Solicitudes' . "\0" . 'idSolicitud', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Solicitudes' . "\0" . 'idEstudiante', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Solicitudes' . "\0" . 'idMonitoria', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Solicitudes' . "\0" . 'cantidadSolicitada', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Solicitudes' . "\0" . 'periodoAcademico');
        }

        return array('__isInitialized__', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Solicitudes' . "\0" . 'idSolicitud', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Solicitudes' . "\0" . 'idEstudiante', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Solicitudes' . "\0" . 'idMonitoria', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Solicitudes' . "\0" . 'cantidadSolicitada', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Solicitudes' . "\0" . 'periodoAcademico');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Solicitudes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstudiante($idEstudiante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstudiante', array($idEstudiante));

        return parent::setIdEstudiante($idEstudiante);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstudiante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstudiante', array());

        return parent::getIdEstudiante();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMonitoria($idMonitoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMonitoria', array($idMonitoria));

        return parent::setIdMonitoria($idMonitoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMonitoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMonitoria', array());

        return parent::getIdMonitoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadSolicitada($cantidadSolicitada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadSolicitada', array($cantidadSolicitada));

        return parent::setCantidadSolicitada($cantidadSolicitada);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadSolicitada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadSolicitada', array());

        return parent::getCantidadSolicitada();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodoAcademico($periodoAcademico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodoAcademico', array($periodoAcademico));

        return parent::setPeriodoAcademico($periodoAcademico);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodoAcademico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodoAcademico', array());

        return parent::getPeriodoAcademico();
    }

}
