<?php

namespace Proxies\__CG__\solicitudMonitoria\EstudianteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Estudiantes extends \solicitudMonitoria\EstudianteBundle\Entity\Estudiantes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'idEstudiante', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'nombre', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'noDocumento', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'tipoDocumento', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'correo', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'telefono', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'semestre', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'promAcumulado');
        }

        return array('__isInitialized__', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'idEstudiante', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'nombre', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'noDocumento', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'tipoDocumento', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'correo', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'telefono', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'semestre', '' . "\0" . 'solicitudMonitoria\\EstudianteBundle\\Entity\\Estudiantes' . "\0" . 'promAcumulado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Estudiantes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoDocumento($noDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoDocumento', array($noDocumento));

        return parent::setNoDocumento($noDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoDocumento', array());

        return parent::getNoDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDocumento($tipoDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDocumento', array($tipoDocumento));

        return parent::setTipoDocumento($tipoDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoDocumento', array());

        return parent::getTipoDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($correo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', array($correo));

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', array());

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setSemestre($semestre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSemestre', array($semestre));

        return parent::setSemestre($semestre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSemestre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSemestre', array());

        return parent::getSemestre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromAcumulado($promAcumulado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromAcumulado', array($promAcumulado));

        return parent::setPromAcumulado($promAcumulado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromAcumulado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromAcumulado', array());

        return parent::getPromAcumulado();
    }

}
